// src/lib/services/WelcomeMessageService.ts - VERSION CORRIGÉE

import type { ChatMessage, ConversationStep } from '@/types/chat';
import { supabase } from '@/lib/supabase';

export class WelcomeMessageService {
  private static instance: WelcomeMessageService;

  public static getInstance(): WelcomeMessageService {
    if (!this.instance) {
      this.instance = new WelcomeMessageService();
    }
    return this.instance;
  }

  /**
   * ✅ GÉNÈRE LE MESSAGE D'ACCUEIL CORRECT - VERSION DESKTOP
   */
  public generateDesktopWelcomeMessage(
    productName: string,
    sessionId: string,
    productId: string,
    productPrice?: number,
    reviewCount?: number
  ): ChatMessage {
    console.log('🖥️ Generating DESKTOP welcome message for:', { productName, sessionId, productId });
    
    return {
      type: 'assistant',
      content: `👋 Bonjour ! Je suis **Rose**, votre Assistante d'achat.

Je vois que vous vous intéressez à notre jeu **${productName}**. C'est excellent ✨

Comment puis-je vous aider ?`,
      // ❌ PAS DE CHOICES ICI - Ils seront gérés par l'interface desktop
      choices: [],
      assistant: {
        name: 'Rose',
        title: 'Assistante d\'achat'
      },
      metadata: {
        nextStep: 'initial_engagement' as ConversationStep,
        productId: productId,
        sessionId: sessionId,
        flags: { 
          isWelcome: true,
          preventAIIntervention: true,
          autoGenerated: true,
          desktopMode: true,
          useInterfaceButtons: true // ✅ Flag pour indiquer d'utiliser les boutons de l'interface
        }
      },
      timestamp: new Date().toISOString()
    };
  }

  /**
   * ✅ GÉNÈRE LE MESSAGE D'ACCUEIL CORRECT - VERSION MOBILE
   */
  public generateMobileWelcomeMessage(
    productName: string,
    sessionId: string,
    productId: string,
    productPrice?: number
  ): ChatMessage {
    console.log('📱 Generating MOBILE welcome message for:', { productName, sessionId, productId });
    
    return {
      type: 'assistant',
      content: `👋 Bonjour ! Je suis **Rose**, votre Assistante d'achat.

Je vois que vous vous intéressez à notre jeu **${productName}**. C'est excellent ✨

Comment puis-je vous aider ?`,
      // ✅ CHOICES POUR MOBILE - Affichés dans le chat
      choices: [
        'Je veux l\'acheter maintenant',
        'J\'ai des questions à poser',
        'Je veux en savoir plus'
      ],
      assistant: {
        name: 'Rose',
        title: 'Assistante d\'achat',
        avatar: undefined
      },
      metadata: {
        nextStep: 'initial_engagement' as ConversationStep,
        productId: productId,
        sessionId: sessionId,
        flags: { 
          isWelcome: true,
          preventAIIntervention: true,
          autoGenerated: true,
          mobileMode: true
        }
      },
      timestamp: new Date().toISOString()
    };
  }

  /**
   * ✅ MÉTHODE GÉNÉRIQUE - Choisit automatiquement la version selon le contexte
   */
  public generateWelcomeMessage(
    productName: string,
    sessionId: string,
    productId: string,
    productPrice?: number,
    isMobile: boolean = false
  ): ChatMessage {
    console.log('🌹 Generating welcome message for:', { productName, sessionId, productId, isMobile });
    
    if (isMobile) {
      return this.generateMobileWelcomeMessage(productName, sessionId, productId, productPrice);
    } else {
      return this.generateDesktopWelcomeMessage(productName, sessionId, productId, productPrice);
    }
  }

  /**
   * ✅ GÈRE LES RÉPONSES AUX BOUTONS D'ACCUEIL
   */
  public async handleWelcomeButtonResponse(
    choice: string,
    productId: string,
    productName: string
  ): Promise<ChatMessage> {
    
    console.log('🌹 Handling welcome button response:', { choice, productId, productName });

    // ✅ CORRECTION: Ne plus traiter "Je veux l'acheter maintenant" ici
    // Cette logique est maintenant gérée directement dans OptimizedChatService
    
    // ✅ 1. "J'ai des questions à poser" → Mode questions libres
    if (choice.includes('questions à poser') || choice.includes('questions')) {
      return {
        type: 'assistant',
        content: `🤔 **Parfait ! Posez-moi toutes vos questions.**

Je connais **${productName}** sur le bout des doigts et je peux vous renseigner sur :

• **Comment y jouer** et les règles
• **Pour qui** c'est adapté
• **Les bénéfices** concrets
• **La livraison** et les délais
• **Tout ce que vous voulez savoir !**

Quelle est votre première question ?`,
        choices: [
          'Comment y jouer ?',
          'C\'est pour qui ?',
          'Quels sont les bénéfices ?'
        ],
        assistant: {
          name: 'Rose',
          title: 'Assistante d\'achat'
        },
        metadata: {
          nextStep: 'question_mode' as ConversationStep,
          productId: productId,
          flags: { 
            questionMode: true,
            openToQuestions: true
          }
        },
        timestamp: new Date().toISOString()
      };
    }

    // ✅ 2. "Je veux en savoir plus" → Description depuis la DB
    if (choice.includes('savoir plus') || choice.includes('en savoir plus')) {
      const productDescription = await this.getProductDescription(productId);
      
      return {
        type: 'assistant',
        content: `✨ **Découvrons ${productName} ensemble**

${productDescription}

Que voulez-vous découvrir en premier ?`,
        choices: [
          'Comment y jouer ?',
          'C\'est pour qui ?',
          'Je veux l\'acheter maintenant'
        ],
        assistant: {
          name: 'Rose',
          title: 'Assistante d\'achat'
        },
        metadata: {
          nextStep: 'product_discovery' as ConversationStep,
          productId: productId,
          flags: { 
            discoveryMode: true,
            detailedInfo: true
          }
        },
        timestamp: new Date().toISOString()
      };
    }

    // ✅ Choix non reconnu - Rediriger
    return {
      type: 'assistant',
      content: `😅 **Je n'ai pas bien compris votre choix.**

Pouvez-vous me dire ce qui vous intéresse le plus ?`,
      choices: [
        'Je veux l\'acheter maintenant',
        'J\'ai des questions à poser',
        'Je veux en savoir plus'
      ],
      assistant: {
        name: 'Rose',
        title: 'Assistante d\'achat'
      },
      metadata: {
        nextStep: 'initial_engagement' as ConversationStep,
        productId: productId,
        flags: { 
          retryWelcome: true
        }
      },
      timestamp: new Date().toISOString()
    };
  }

  /**
   * ✅ RÉCUPÈRE LA DESCRIPTION PRODUIT DEPUIS LA BASE DE DONNÉES
   */
  private async getProductDescription(productId: string): Promise<string> {
    try {
      const { data, error } = await supabase
        .from('products')
        .select('description, name')
        .eq('id', productId)
        .single();

      if (error || !data) {
        console.error('❌ Error fetching product description:', error);
        return 'Un jeu de cartes révolutionnaire qui transforme vos conversations ordinaires en moments profonds et authentiques.';
      }

      return data.description || `${data.name} est un jeu de cartes conçu pour renforcer les liens humains à travers des conversations significatives.`;
      
    } catch (error) {
      console.error('❌ Database error:', error);
      return 'Un jeu de cartes révolutionnaire qui transforme vos conversations ordinaires en moments profonds et authentiques.';
    }
  }

  /**
   * ✅ VÉRIFIE SI UN MESSAGE EST UNE RÉPONSE AU MESSAGE D'ACCUEIL
   */
  public isWelcomeResponse(message: string): boolean {
    const welcomeResponses = [
      'je veux l\'acheter maintenant',
      'j\'ai des questions à poser',
      'je veux en savoir plus',
      'acheter maintenant',
      'questions à poser',
      'savoir plus'
    ];
    
    return welcomeResponses.some(response => 
      message.toLowerCase().includes(response.toLowerCase())
    );
  }

  /**
   * ✅ GÉNÈRE UN MESSAGE DE RÉCUPÉRATION EN CAS D'ERREUR
   */
  public generateRecoveryMessage(productName: string, productId: string): ChatMessage {
    return {
      type: 'assistant',
      content: `😊 **Pas de souci ! Recommençons.**

Je suis Rose, votre assistante pour **${productName}**.

Comment puis-je vous aider aujourd'hui ?`,
      choices: [
        'Je veux l\'acheter maintenant',
        'J\'ai des questions à poser',
        'Je veux en savoir plus'
      ],
      assistant: {
        name: 'Rose',
        title: 'Assistante d\'achat'
      },
      metadata: {
        nextStep: 'initial_engagement' as ConversationStep,
        productId: productId,
        flags: { 
          isRecovery: true
        }
      },
      timestamp: new Date().toISOString()
    };
  }
}