// src/lib/services/WelcomeMessageService.ts - VERSION CORRIGÉE AVEC VRAIES DONNÉES SUPABASE

import type { ChatMessage, ConversationStep } from '@/types/chat';
import { supabase } from '@/lib/supabase';

export class WelcomeMessageService {
  private static instance: WelcomeMessageService;

  public static getInstance(): WelcomeMessageService {
    if (!this.instance) {
      this.instance = new WelcomeMessageService();
    }
    return this.instance;
  }

  /**
   * ✅ GÉNÈRE LE MESSAGE D'ACCUEIL CORRECT - VERSION DESKTOP
   */
  public generateDesktopWelcomeMessage(
    productName: string,
    sessionId: string,
    productId: string,
    productPrice?: number,
    reviewCount?: number
  ): ChatMessage {
    console.log('🖥️ Generating DESKTOP welcome message for:', { productName: `le jeu ${productName}`, sessionId, productId });
    
    return {
      type: 'assistant',
      content: `👋 Bonjour ! Je suis **Rose**, votre Assistante d'achat.

Je vois que vous vous intéressez à notre **jeu ${productName}**. C'est excellent ✨

Comment puis-je vous aider ?`,
      // ❌ PAS DE CHOICES ICI - Ils seront gérés par l'interface desktop
      choices: [],
      assistant: {
        name: 'Rose',
        title: 'Assistante d\'achat'
      },
      metadata: {
        nextStep: 'initial_engagement' as ConversationStep,
        productId: productId,
        sessionId: sessionId,
        flags: { 
          isWelcome: true,
          preventAIIntervention: true,
          autoGenerated: true,
          desktopMode: true,
          useInterfaceButtons: true // ✅ Flag pour indiquer d'utiliser les boutons de l'interface
        }
      },
      timestamp: new Date().toISOString()
    };
  }

  /**
   * ✅ GÉNÈRE LE MESSAGE D'ACCUEIL CORRECT - VERSION MOBILE
   */
  public generateMobileWelcomeMessage(
    productName: string,
    sessionId: string,
    productId: string,
    productPrice?: number
  ): ChatMessage {
    console.log('📱 Generating MOBILE welcome message for:', { productName: `le jeu ${productName}`, sessionId, productId });
    
    return {
      type: 'assistant',
      content: `👋 Bonjour ! Je suis **Rose**, votre Assistante d'achat.

Je vois que vous vous intéressez à notre **jeu ${productName}**. C'est excellent ✨

Comment puis-je vous aider ?`,
      // ✅ CHOICES POUR MOBILE - Affichés dans le chat
      choices: [
        'Je veux l\'acheter maintenant',
        'J\'ai des questions à poser',
        'Je veux en savoir plus'
      ],
      assistant: {
        name: 'Rose',
        title: 'Assistante d\'achat',
        avatar: undefined
      },
      metadata: {
        nextStep: 'initial_engagement' as ConversationStep,
        productId: productId,
        sessionId: sessionId,
        flags: { 
          isWelcome: true,
          preventAIIntervention: true,
          autoGenerated: true,
          mobileMode: true
        }
      },
      timestamp: new Date().toISOString()
    };
  }

  /**
   * ✅ MÉTHODE GÉNÉRIQUE - Choisit automatiquement la version selon le contexte
   */
  public generateWelcomeMessage(
    productName: string,
    sessionId: string,
    productId: string,
    productPrice?: number,
    isMobile: boolean = false
  ): ChatMessage {
    console.log('🌹 Generating welcome message for:', { productName: `le jeu ${productName}`, sessionId, productId, isMobile });
    
    if (isMobile) {
      return this.generateMobileWelcomeMessage(productName, sessionId, productId, productPrice);
    } else {
      return this.generateDesktopWelcomeMessage(productName, sessionId, productId, productPrice);
    }
  }
  
  // ✅ GÈRE LES RÉPONSES AUX BOUTONS D'ACCUEIL - VERSION CORRIGÉE AVEC VRAIES DONNÉES
  public async handleWelcomeButtonResponse(
    choice: string,
    productId: string,
    productName: string
  ): Promise<ChatMessage> {
    
    console.log('🌹 Handling welcome button response:', { choice, productId, productName: `le jeu ${productName}` });

    // ✅ 1. "J'ai des questions à poser" → Mode questions libres activé
    if (choice.includes('questions à poser') || choice.includes('questions')) {
      return {
        type: 'assistant',
        content: `🤔 **Excellent ! Je suis là pour ça.**

Vous pouvez me poser librement toutes les questions que vous souhaitez au sujet du **jeu ${productName}**, de la marque VIENS ON S'CONNAÎT, de l'application mobile, ou même de nos autres jeux.

**Quelques exemples :**
- "Comment y jouer exactement ?"
- "Ce jeu est-il adapté à mon couple ?"
- "Combien de temps dure une partie ?"
- "Comment fonctionne la livraison ?"
- "Quels sont les autres jeux disponibles ?"

**Qu'aimeriez-vous savoir ?** 💭

*Vous pouvez taper votre question ou utiliser le micro 🎤*`,
        choices: [
          'Comment y jouer ?',
          'C\'est pour qui exactement ?',
          'Combien coûte la livraison ?',
          'Je veux l\'acheter maintenant'
        ],
        assistant: {
          name: 'Rose',
          title: 'Assistante d\'achat'
        },
        metadata: {
          nextStep: 'free_text_mode' as ConversationStep,
          productId: productId,
          flags: { 
            freeTextEnabled: true,
            questionMode: true,
            openToQuestions: true,
            aiPriorityEnabled: true // ✅ Active la priorité IA pour ce mode
          }
        },
        timestamp: new Date().toISOString()
      };
    }

    // ✅ 2. "Je veux en savoir plus" → Description VRAIE depuis la base de données
    if (choice.includes('savoir plus') || choice.includes('en savoir plus')) {
      try {
        console.log('📋 Fetching REAL product description for:', productId);
        
        // ✅ RÉCUPÉRER LA VRAIE DESCRIPTION depuis la base
        const { data: productInfo, error } = await supabase
          .from('products')
          .select('description, game_rules, target_audience, benefits')
          .eq('id', productId)
          .single();

        if (error) {
          console.error('❌ Error fetching product info:', error);
          // Fallback avec description générique
          return this.createGenericProductInfo(productName, productId);
        }

        const description = productInfo.description || `Le **jeu ${productName}** est un jeu de cartes révolutionnaire qui transforme vos conversations ordinaires en moments profonds et authentiques.`;
        
        return {
          type: 'assistant',
          content: `✨ **Découvrons le jeu ${productName} ensemble**

${description}

**Que voulez-vous découvrir en premier ?**`,
          choices: [
            'Comment y jouer ?',
            'Je veux l\'acheter maintenant',
            'Voir les témoignages',
            'J\'ai d\'autres questions'
          ],
          assistant: {
            name: 'Rose',
            title: 'Assistante d\'achat'
          },
          metadata: {
            nextStep: 'product_discovery' as ConversationStep,
            productId: productId,
            flags: { 
              discoveryMode: true,
              detailedInfo: true,
              showGameRules: !!productInfo.game_rules,
              showTargetAudience: !!productInfo.target_audience,
              realDataUsed: true
            }
          },
          timestamp: new Date().toISOString()
        };

      } catch (error) {
        console.error('❌ Database error:', error);
        return this.createGenericProductInfo(productName, productId);
      }
    }

    // ✅ 3. Gestion des questions spécifiques depuis la description
    if (choice.includes('Comment y jouer')) {
      return await this.handleGameRulesRequest(productId, productName);
    }

    if (choice.includes('Voir les témoignages')) {
      return await this.handleTestimonialsRequest(productId, productName);
    }

    // ✅ 4. "Je veux l'acheter maintenant" → Déclenchement du flow express
    if (choice.includes('acheter maintenant') || choice.includes('Je veux l\'acheter')) {
      return {
        type: 'assistant',
        content: `🛒 **Parfait ! Commençons votre commande**

Le **jeu ${productName}** - Excellent choix ! 🎉

Combien d'exemplaires voulez-vous ?`,
        choices: [
          '1 exemplaire',
          '2 exemplaires',
          '3 exemplaires', 
          'Autre quantité'
        ],
        assistant: {
          name: 'Rose',
          title: 'Assistante d\'achat'
        },
        metadata: {
          nextStep: 'express_quantity' as ConversationStep,
          productId: productId,
          flags: { 
            expressMode: true,
            quantitySelection: true,
            purchaseInitiated: true
          }
        },
        timestamp: new Date().toISOString()
      };
    }

    // ✅ Choix non reconnu - Rediriger vers IA
    console.log('🤖 Unrecognized choice, using AI to handle:', choice);
    return {
      type: 'assistant',
      content: `🤔 **Intéressant ! Laissez-moi vous aider avec ça.**

Concernant le **jeu ${productName}**, que souhaitez-vous savoir précisément ?`,
      choices: [
        'Je veux l\'acheter maintenant',
        'J\'ai des questions à poser',
        'Je veux en savoir plus',
        'Comment y jouer ?'
      ],
      assistant: {
        name: 'Rose',
        title: 'Assistante d\'achat'
      },
      metadata: {
        nextStep: 'ai_response' as ConversationStep,
        productId: productId,
        flags: { 
          aiRedirect: true,
          unrecognizedChoice: true,
          needsAIProcessing: true
        }
      },
      timestamp: new Date().toISOString()
    };
  }

  // ✅ NOUVELLE MÉTHODE: Gestion des règles du jeu avec VRAIES DONNÉES
  private async handleGameRulesRequest(productId: string, productName: string): Promise<ChatMessage> {
    try {
      console.log('🎮 Fetching REAL game rules for:', productId);
      
      const { data: productInfo, error } = await supabase
        .from('products')
        .select('game_rules')
        .eq('id', productId)
        .single();

      if (error || !productInfo?.game_rules) {
        console.log('⚠️ No game rules found, using generic rules');
        // Règles génériques
        return {
          type: 'assistant',
          content: `🎮 **Comment jouer au jeu ${productName} :**

**C'est très simple :**
1️⃣ Mélangez les 150 cartes
2️⃣ Tirez une carte chacun votre tour
3️⃣ Lisez la question à voix haute
4️⃣ Répondez sincèrement
5️⃣ Échangez sur vos réponses

🎯 **Objectif :** Créer des conversations authentiques !

⏰ **Durée :** 15 min (express) à 2h+ (marathon)`,
          choices: [
            'Je veux l\'acheter maintenant',
            'Voir les témoignages',
            'J\'ai d\'autres questions'
          ],
          assistant: { name: 'Rose', title: 'Assistante d\'achat' },
          metadata: {
            nextStep: 'game_rules_shown' as ConversationStep,
            productId: productId,
            flags: { gameRulesShown: true, genericRules: true }
          },
          timestamp: new Date().toISOString()
        };
      }

      // Utiliser les vraies règles depuis la base
      console.log('✅ Using REAL game rules from database');
      return {
        type: 'assistant',
        content: `🎮 **Comment jouer au jeu ${productName} :**

${productInfo.game_rules}`,
        choices: [
          'Je veux l\'acheter maintenant',
          'Voir les témoignages',
          'J\'ai d\'autres questions'
        ],
        assistant: { name: 'Rose', title: 'Assistante d\'achat' },
        metadata: {
          nextStep: 'game_rules_shown' as ConversationStep,
          productId: productId,
          flags: { gameRulesShown: true, realDataUsed: true }
        },
        timestamp: new Date().toISOString()
      };

    } catch (error) {
      console.error('❌ Error fetching game rules:', error);
      return this.createGenericGameRules(productName, productId);
    }
  }

  // ✅ NOUVELLE MÉTHODE: Gestion des témoignages avec VRAIES DONNÉES
  private async handleTestimonialsRequest(productId: string, productName: string): Promise<ChatMessage> {
    try {
      console.log('⭐ Fetching REAL testimonials for:', productId);
      
      const { data: testimonials, error } = await supabase
        .from('testimonials')
        .select('customer_name, content, rating')
        .eq('product_id', productId)
        .eq('is_active', true)
        .order('created_at', { ascending: false })
        .limit(3);

      if (error || !testimonials || testimonials.length === 0) {
        console.log('⚠️ No testimonials found, using generic message');
        return {
          type: 'assistant',
          content: `⭐ **Témoignages pour le jeu ${productName} :**

Les témoignages arrivent bientôt ! En attendant, je peux vous dire que ce jeu a déjà aidé des milliers de couples et familles à créer des liens plus forts.

Voulez-vous en savoir plus sur le jeu ?`,
          choices: [
            'Je veux l\'acheter maintenant',
            'Comment y jouer ?',
            'J\'ai d\'autres questions'
          ],
          assistant: { name: 'Rose', title: 'Assistante d\'achat' },
          metadata: {
            nextStep: 'testimonials_empty' as ConversationStep,
            productId: productId,
            flags: { testimonialsRequested: true, noTestimonials: true }
          },
          timestamp: new Date().toISOString()
        };
      }

      // Afficher les vrais témoignages
      console.log(`✅ Using ${testimonials.length} REAL testimonials from database`);
      
      const testimonialsText = testimonials.map(t => 
        `**${t.customer_name}** (${t.rating}/5 ⭐)
"${t.content}"`
      ).join('\n\n');

      return {
        type: 'assistant',
        content: `⭐ **Témoignages pour le jeu ${productName} :**

${testimonialsText}

Ces témoignages vous donnent-ils envie d'essayer ?`,
        choices: [
          'Je veux l\'acheter maintenant',
          'Comment y jouer ?',
          'J\'ai d\'autres questions'
        ],
        assistant: { name: 'Rose', title: 'Assistante d\'achat' },
        metadata: {
          nextStep: 'testimonials_shown' as ConversationStep,
          productId: productId,
          flags: { testimonialsShown: true, realDataUsed: true }
        },
        timestamp: new Date().toISOString()
      };

    } catch (error) {
      console.error('❌ Error fetching testimonials:', error);
      return this.createGenericTestimonials(productName, productId);
    }
  }

  // ✅ MÉTHODES DE FALLBACK GÉNÉRIQUES

  private createGenericProductInfo(productName: string, productId: string): ChatMessage {
    return {
      type: 'assistant',
      content: `✨ **Le jeu ${productName}**

Un jeu de cartes révolutionnaire qui transforme vos conversations ordinaires en moments profonds et authentiques. Chaque partie crée des liens plus forts entre les joueurs.

**Caractéristiques :**
- 150 cartes soigneusement conçues
- Conversations profondes et bienveillantes
- Adapté à votre situation spécifique
- Résultats visibles dès la première partie

**Que voulez-vous découvrir en premier ?**`,
      choices: [
        'Comment y jouer ?',
        'Je veux l\'acheter maintenant',
        'J\'ai d\'autres questions'
      ],
      assistant: { name: 'Rose', title: 'Assistante d\'achat' },
      metadata: {
        nextStep: 'product_discovery' as ConversationStep,
        productId: productId,
        flags: { genericFallback: true }
      },
      timestamp: new Date().toISOString()
    };
  }

  private createGenericGameRules(productName: string, productId: string): ChatMessage {
    return {
      type: 'assistant',
      content: `🎮 **Comment jouer au jeu ${productName} :**

**C'est très simple :**
1️⃣ Mélangez les 150 cartes
2️⃣ Tirez une carte chacun votre tour
3️⃣ Lisez la question à voix haute
4️⃣ Répondez sincèrement
5️⃣ Échangez sur vos réponses

🎯 **Objectif :** Créer des conversations authentiques !
⏰ **Durée :** 15 min (express) à 2h+ (marathon)`,
      choices: [
        'Je veux l\'acheter maintenant',
        'Voir les témoignages',
        'J\'ai d\'autres questions'
      ],
      assistant: { name: 'Rose', title: 'Assistante d\'achat' },
      metadata: {
        nextStep: 'game_rules_shown' as ConversationStep,
        productId: productId,
        flags: { gameRulesShown: true, genericFallback: true }
      },
      timestamp: new Date().toISOString()
    };
  }

  private createGenericTestimonials(productName: string, productId: string): ChatMessage {
    return {
      type: 'assistant',
      content: `⭐ **Témoignages pour le jeu ${productName} :**

Nos clients adorent ce jeu ! Il a déjà aidé des milliers de couples et familles à créer des liens plus forts au Sénégal et en Afrique.

Les témoignages détaillés arrivent bientôt. En attendant, voulez-vous essayer le jeu ?`,
      choices: [
        'Je veux l\'acheter maintenant',
        'Comment y jouer ?',
        'J\'ai d\'autres questions'
      ],
      assistant: { name: 'Rose', title: 'Assistante d\'achat' },
      metadata: {
        nextStep: 'testimonials_generic' as ConversationStep,
        productId: productId,
        flags: { testimonialsRequested: true, genericFallback: true }
      },
      timestamp: new Date().toISOString()
    };
  }

  /**
   * ✅ VÉRIFIE SI UN MESSAGE EST UNE RÉPONSE AU MESSAGE D'ACCUEIL
   */
  public isWelcomeResponse(message: string): boolean {
    const welcomeResponses = [
      'je veux l\'acheter maintenant',
      'j\'ai des questions à poser',
      'je veux en savoir plus',
      'acheter maintenant',
      'questions à poser',
      'savoir plus'
    ];
    
    return welcomeResponses.some(response => 
      message.toLowerCase().includes(response.toLowerCase())
    );
  }

  /**
   * ✅ GÉNÈRE UN MESSAGE DE RÉCUPÉRATION EN CAS D'ERREUR
   */
  public generateRecoveryMessage(productName: string, productId: string): ChatMessage {
    return {
      type: 'assistant',
      content: `😊 **Pas de souci ! Recommençons.**

Je suis Rose, votre assistante pour le **jeu ${productName}**.

Comment puis-je vous aider aujourd'hui ?`,
      choices: [
        'Je veux l\'acheter maintenant',
        'J\'ai des questions à poser',
        'Je veux en savoir plus'
      ],
      assistant: {
        name: 'Rose',
        title: 'Assistante d\'achat'
      },
      metadata: {
        nextStep: 'initial_engagement' as ConversationStep,
        productId: productId,
        flags: { 
          isRecovery: true
        }
      },
      timestamp: new Date().toISOString()
    };
  }
}